import jsPDF from 'jspdf';
import type { PsychReport, RemedyData } from '../services/api';

interface Message {
  role: "user" | "assistant";
  content: string;
  report?: PsychReport;
  remedy?: RemedyData;
  fusionScore?: number;
}

export const generateChatPDF = (messages: Message[], date: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 20;
  let marginY = 20;
  const contentWidth = pageWidth - (marginX * 2);

  // Helper function to handle page breaks
  const checkPageBreak = (requiredSpace: number) => {
    if (marginY + requiredSpace > pageHeight - 20) {
      doc.addPage();
      marginY = 20;
      return true;
    }
    return false;
  };

  // --- HEADER ---
  doc.setFillColor(79, 70, 229); // Indigo-600
  doc.rect(0, 0, pageWidth, 15, 'F');
  
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(79, 70, 229);
  doc.text("PsyPredict", marginX, marginY + 10);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("Comprehensive Clinical AI Assessment", marginX, marginY + 18);
  
  // Align date to the right
  const dateStr = `Date: ${new Date(date).toLocaleString()}`;
  const dateWidth = doc.getTextWidth(dateStr);
  doc.text(dateStr, pageWidth - marginX - dateWidth, marginY + 18);
  
  marginY += 30;

  // --- DISCLAIMER BOX ---
  doc.setFillColor(254, 242, 242); // Red-50
  doc.setDrawColor(252, 165, 165); // Red-300
  doc.setLineWidth(0.5);
  doc.roundedRect(marginX, marginY, contentWidth, 22, 3, 3, 'FD');
  
  doc.setFontSize(10);
  doc.setTextColor(185, 28, 28); // Red-700
  doc.setFont("helvetica", "bold");
  doc.text("MEDICAL DISCLAIMER", marginX + 5, marginY + 6);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const disclaimerText = "This record is generated by an automated AI system for educational and preliminary screening purposes. It is NOT a verified medical diagnosis, prescription, or professional psychiatric evaluation. Please share this document with a certified healthcare professional. In case of an emergency or crisis, contact local emergency services immediately.";
  const splitDisclaimer = doc.splitTextToSize(disclaimerText, contentWidth - 10);
  doc.text(splitDisclaimer, marginX + 5, marginY + 11);
  
  marginY += 35;

  // --- TRANSCRIPT & ASSESSMENT CONTENT ---
  messages.forEach((msg) => {
    checkPageBreak(20);
    const isUser = msg.role === 'user';
    const roleTitle = isUser ? "Client" : "PsyPredict AI";
    
    // Draw role badge
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(isUser ? 79 : 100, isUser ? 70 : 100, isUser ? 229 : 100); // User indigo, AI gray
    doc.text(roleTitle, marginX, marginY);
    marginY += 6;
    
    // Message Content
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 30);
    const splitContent = doc.splitTextToSize(msg.content, contentWidth);
    
    // Calculate content height and check page break inside message
    const contentHeight = splitContent.length * 5;
    checkPageBreak(contentHeight + 10);
    
    doc.text(splitContent, marginX, marginY);
    marginY += contentHeight + 5;

    // --- RENDER CLINICAL REPORT (If Assistant) ---
    if (!isUser && msg.report) {
      checkPageBreak(50); // Ensure space for the box start
      
      const r = msg.report;
      
      // Draw Assessment Box
      doc.setFillColor(248, 250, 252); // Slate-50
      doc.setDrawColor(203, 213, 225); // Slate-300
      
      // We will draw a line on the left to denote it's an assessment
      doc.setLineWidth(1.5);
      doc.setDrawColor(79, 70, 229); // Indigo line
      doc.line(marginX, marginY, marginX, marginY + 5); // placeholder line, we'll draw rect
      
      marginY += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(79, 70, 229);
      doc.text("CLINICAL ASSESSMENT SUMMARY", marginX + 5, marginY);
      marginY += 6;

      // Risk Level
      doc.setFont("helvetica", "bold");
      doc.setTextColor(80, 80, 80);
      doc.text("Risk Classification:", marginX + 5, marginY);
      doc.setFont("helvetica", "normal");
      
      // Color code risk securely
      if (r.risk_classification === "CRITICAL" || r.risk_classification === "HIGH") doc.setTextColor(220, 38, 38);
      else if (r.risk_classification === "MODERATE") doc.setTextColor(202, 138, 4);
      else doc.setTextColor(22, 163, 74);
      
      doc.text(r.risk_classification, marginX + 45, marginY);
      marginY += 6;
      
      // Emotional State
      doc.setTextColor(80, 80, 80);
      doc.setFont("helvetica", "bold");
      doc.text("Emotional State:", marginX + 5, marginY);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);
      const splitEmotion = doc.splitTextToSize(r.emotional_state_summary, contentWidth - 45);
      doc.text(splitEmotion, marginX + 38, marginY);
      marginY += (splitEmotion.length * 5) + 1;

      // Inference
      checkPageBreak(25);
      doc.setTextColor(80, 80, 80);
      doc.setFont("helvetica", "bold");
      doc.text("Behavioral Inference:", marginX + 5, marginY);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);
      const splitInference = doc.splitTextToSize(r.behavioral_inference, contentWidth - 45);
      doc.text(splitInference, marginX + 45, marginY);
      marginY += (splitInference.length * 5) + 1;

      // Interventions
      if (r.suggested_interventions && r.suggested_interventions.length > 0) {
        checkPageBreak(30);
        doc.setTextColor(80, 80, 80);
        doc.setFont("helvetica", "bold");
        doc.text("Interventions:", marginX + 5, marginY);
        marginY += 5;
        doc.setFont("helvetica", "normal");
        doc.setTextColor(40, 40, 40);
        
        r.suggested_interventions.forEach(intervention => {
          const splitInv = doc.splitTextToSize("• " + intervention, contentWidth - 15);
          checkPageBreak(splitInv.length * 5);
          doc.text(splitInv, marginX + 10, marginY);
          marginY += splitInv.length * 5;
        });
        marginY += 2;
      }
      
      // Draw left border line for the whole section
      // Not drawing full box to handle dynamic page breaks safely
      
      // --- RENDER REMEDY (If available) ---
      if (msg.remedy) {
        checkPageBreak(40);
        marginY += 4;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(217, 119, 6); // Amber-600
        doc.text("ANCIENT WISDOM & CARE PLAN", marginX + 5, marginY);
        marginY += 6;
        
        doc.setFontSize(9);
        doc.setTextColor(80, 80, 80);
        doc.text("Gita Wisdom:", marginX + 5, marginY);
        doc.setFont("helvetica", "italic");
        doc.setTextColor(60, 60, 60);
        const splitGita = doc.splitTextToSize(`"${msg.remedy.gita_remedy}"`, contentWidth - 35);
        doc.text(splitGita, marginX + 28, marginY);
        marginY += (splitGita.length * 5) + 3;
        
        doc.setFont("helvetica", "bold");
        doc.text("Medication Ref:", marginX + 5, marginY);
        doc.setFont("helvetica", "normal");
        const splitMeds = doc.splitTextToSize(`${msg.remedy.medications} (${msg.remedy.dosage})`, contentWidth - 35);
        doc.text(splitMeds, marginX + 32, marginY);
        marginY += (splitMeds.length * 5) + 3;
      }
      
      marginY += 8; // Spacing after assessment block
    }
  });

  // --- FOOTER (Page Numbers) ---
  const pageCount = doc.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    // Add top border for footer
    doc.setDrawColor(226, 232, 240);
    doc.line(marginX, pageHeight - 15, pageWidth - marginX, pageHeight - 15);
    
    doc.text(`PsyPredict Consultation Record • Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 8, { align: 'center' });
    
    // Add document id/timestamp
    doc.text(`Ref: ${new Date().getTime().toString(16).toUpperCase()}`, pageWidth - marginX - 25, pageHeight - 8);
  }

  doc.save(`PsyPredict_Clinical_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
