import jsPDF from 'jspdf';

interface Message {
  role: "user" | "assistant";
  content: string;
}

export const generateChatPDF = (messages: Message[], date: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let y = margin;

  // --- HEADER ---
  doc.setFontSize(22);
  doc.setTextColor(79, 70, 229); // Indigo-600
  doc.text("PsyPredict Consultation Record", margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Date: ${new Date(date).toLocaleString()}`, margin, y);
  y += 15;

  // --- DISCLAIMER ---
  doc.setFillColor(254, 242, 242); // Red-50
  doc.setDrawColor(252, 165, 165); // Red-300
  doc.roundedRect(margin, y, contentWidth, 20, 3, 3, 'FD');
  
  doc.setFontSize(10);
  doc.setTextColor(185, 28, 28); // Red-700
  doc.setFont("helvetica", "bold");
  doc.text("MEDICAL DISCLAIMER:", margin + 5, y + 8);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const disclaimerText = "This record is generated by an AI system. It is NOT a medical diagnosis or prescription. Provide this document to a certified medical professional for review. In case of emergency, contact local authorities immediately.";
  const splitDisclaimer = doc.splitTextToSize(disclaimerText, contentWidth - 10);
  doc.text(splitDisclaimer, margin + 5, y + 14);
  
  y += 30;

  // --- CONTENT ---
  doc.setFontSize(12);
  doc.setTextColor(0);

  messages.forEach((msg) => {
    // Check for new page
    if (y > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }

    const isUser = msg.role === 'user';
    const roleTitle = isUser ? "User:" : "Assistant:";
    
    doc.setFont("helvetica", "bold");
    doc.setTextColor(isUser ? 79 : 0, isUser ? 70 : 0, isUser ? 229 : 0); // User blue, AI black
    doc.text(roleTitle, margin, y);
    
    // Message Content
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);
    const splitContent = doc.splitTextToSize(msg.content, contentWidth);
    
    // Calculate if content fits
    const contentHeight = splitContent.length * 5;
    if (y + 5 + contentHeight > pageHeight - margin) {
      doc.addPage();
      y = margin;
      doc.setFont("helvetica", "bold"); // Reset font for next iteration if needed (though we just printed role)
      // Actually, if we just split across pages it's complex. 
      // Simplified: Just push content to next page if it doesn't fit mostly.
    }

    doc.text(splitContent, margin, y + 6);
    y += 6 + contentHeight + 5; // Spacing
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} - Generated via PsyPredict`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  doc.save(`PsyPredict_Consultation_${new Date().toISOString().split('T')[0]}.pdf`);
};
